sonar.projectKey=mr-lenas
sonar.projectName=Mr. Leñas
sonar.host.url=http://sonarqube:9000
sonar.login=sqp_9a27bd0be54af1522d4bf3084c6d92df9a825c39

sonar.sources=mr-lenas-frontend/src,mr-lenas-backend/app,mr-lenas-ml
sonar.exclusions=**/node_modules/**,**/vendor/**,**/__pycache__/**,**/migrations/**